name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
#      CONDA: C:\Miniconda37-x64
      INSTALL_DIR: C:\ECMWF
      SOURCE_DIRECTORY: eccodes-2.35.0-Source
      SOURCE_TAR: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.35.0-Source.tar.gz?api=v2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: git config --global core.symlinks true

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        miniconda-version: "latest"
        auto-activate-base: true
        activate-environment: ""
#      run: |
#        call $env:CONDA\Scripts\activate.bat
#        conda config --set always_yes yes

    - name: Download and extract source
      run: |
        curl -o sources.tar.gz $env:SOURCE_TAR
        7z x -tgzip -so sources.tar.gz | 7z x -si -ttar

    - name: Install Linux utils from msys
      run: |
        conda install -c msys2 m2-bash m2-findutils m2-coreutils m2-grep m2-sed m2-gawk m2-diffutils m2-perl

    - name: Install cmake and other dependencies
      run: |
        conda install -c conda-forge cmake
        conda install libpng openjpeg

    - name: Set up Visual Studio environment
      run: cmd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

    - name: Build and install
      run: |
        cd $env:SOURCE_DIRECTORY
        mkdir BUILD
        cd BUILD
        cmake -G "NMake Makefiles" ^
          -D CMAKE_INSTALL_PREFIX=$env:INSTALL_DIR ^
          -D CMAKE_BUILD_TYPE=Release ^
          -D ENABLE_FORTRAN=0 ^
          -D ENABLE_PYTHON=0 ^
          -D ENABLE_NETCDF=0 ^
          -D ENABLE_PNG=1 ^
          -D ENABLE_JPG=1 ^
          -D OPENJPEG_INCLUDE_DIR=$env:CONDA\Library\include\openjpeg-2.4.0 ^
          -D IEEE_LE=1 ^
          -D ENABLE_EXAMPLES=0 ^
          -D ENABLE_MEMFS=0 ^
          -D ENABLE_TESTS=0 ^
          -D ENABLE_EXTRA_TESTS=OFF ^
          ..
        nmake install
        copy "$env:CONDA\Library\bin\openjp2.dll" "$env:INSTALL_DIR\bin\"
        copy "$env:CONDA\Library\bin\libpng16.dll" "$env:INSTALL_DIR\bin\"
        copy "$env:CONDA\Library\bin\zlib.dll" "$env:INSTALL_DIR\bin\"

    - name: Run tests
      run: cmd "$env:INSTALL_DIR\bin\codes_info.exe"

    - name: Package artifacts
      run: |
        cd C:\
        7z a "$env:GITHUB_WORKSPACE\EcCodes-win-x64.zip" "$env:INSTALL_DIR"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: EcCodes-win-x64
        path: EcCodes-win-x64.zip
